const mentorsData = [
    {
        name: "Curious George",
        profession: "UI UX Design",
        tasks: 40,
        rate: 4.7,
        reviews: 750,
        image: '/img/girl.png',
        isFollowed: false,
    },
    {
        name: "Abraham Lincoln",
        profession: "3D Design",
        tasks: 32,
        rate: 4.9,
        reviews: 510,
        image: '/img/girl.png',
        isFollowed: true,
    },
    {
        name: "Jessica Jane",
        profession: "Web Developer",
        tasks: 40,
        rate: 4.7,
        reviews: 750,
        image: '/img/girl.png',
        isFollowed: false,
    },
    {
        name: "Alex Stanton",
        profession: "UI / UX Designer",
        tasks: 60,
        rate: 4.9,
        reviews: 970,
        image: '/img/girl.png',
        isFollowed: true,
    },
    {
        name: "Antoine Griezmann",
        profession: "Android Developer",
        tasks: 50,
        rate: 4.8,
        reviews: 830,
        image: '/img/girl.png',
        isFollowed: false,
    },
    {
        name: "Anna White",
        profession: "3D Design",
        tasks: 60,
        rate: 4.8,
        reviews: 870,
        image: '/img/girl.png',
        isFollowed: true,
    },
    {
        name: "Richard Kyle",
        profession: "2D Design",
        tasks: 60,
        rate: 4.7,
        reviews: 730,
        image: '/img/girl.png',
        isFollowed: false,
    },
    {
        name: "Julia Philips",
        profession: "IOS Developer",
        tasks: 60,
        rate: 4.9,
        reviews: 910,
        image: '/img/girl.png',
        isFollowed: true,
    }
];

export default mentorsData;