const tasksData = [
    {
        title: "Creating Fresh Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-04 12:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Color Palettes",
        tag: "UI UX Design",
        progress: 100,
        expire: "2025-12-04 14:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Mobile App Design",
        tag: "UI UX Design",
        progress: 75,
        expire: "2025-12-04 15:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Perfect Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-05 04:00",
        image: '/img/task.png',
    },
    {
        title: "Mobile App Design",
        tag: "UI UX Design",
        progress: 65,
        expire: "2025-12-06 00:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Awesome Mobile Apps",
        tag: "UI UX Design",
        progress: 90,
        expire: "2025-12-04 00:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Fresh Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-04 12:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Color Palettes",
        tag: "UI UX Design",
        progress: 100,
        expire: "2025-12-04 14:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Mobile App Design",
        tag: "UI UX Design",
        progress: 75,
        expire: "2025-12-07 15:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Perfect Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-08 04:00",
        image: '/img/task.png',
    },
    {
        title: "Mobile App Design",
        tag: "UI UX Design",
        progress: 65,
        expire: "2025-12-07 00:00",
        image: '/img/task.png',
    },

    {
        title: "Creating Fresh Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-04 12:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Color Palettes",
        tag: "UI UX Design",
        progress: 100,
        expire: "2025-12-04 14:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Mobile App Design",
        tag: "UI UX Design",
        progress: 75,
        expire: "2025-12-04 15:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Perfect Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-05 04:00",
        image: '/img/task.png',
    },
    {
        title: "Mobile App Design",
        tag: "UI UX Design",
        progress: 65,
        expire: "2025-12-06 00:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Awesome Mobile Apps",
        tag: "UI UX Design",
        progress: 90,
        expire: "2025-12-04 00:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Fresh Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-04 12:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Color Palettes",
        tag: "UI UX Design",
        progress: 100,
        expire: "2025-12-07 14:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Mobile App Design",
        tag: "UI UX Design",
        progress: 75,
        expire: "2025-12-08 15:00",
        image: '/img/task.png',
    },
    {
        title: "Creating Perfect Website",
        tag: "Web Developer",
        progress: 85,
        expire: "2025-12-09 04:00",
        image: '/img/task.png',
    },
    {
        title: "Mobile App Design",
        tag: "UI UX Design",
        progress: 65,
        expire: "2025-12-10 00:00",
        image: '/img/task.png',
    },

];

export default tasksData;